application: freizll
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: helloapp.py
- url: /hzbus/.*
  script: hzbus.py
- url: /stylesheets
  static_dir: stylesheets
- url: /javascripts
  static_dir: javascripts

